// Generated by LiveScript 1.4.0
var onIdle, map, x;
onIdle = require('on-idle');
map = require('prelude-ls').map;
x = function(a){
  return onIdle(function(){
    return console.log(a
      ? 'hello'
      : map(function(it){
        return it.x;
      }, [12345]));
  });
};
x();